### ISSUE TITLE
create a bcrypt util

### ISSUE THREAD

**Issue by Darkmift** [Darkmift/ELEVATION-ITWORKS#38]
#### **Description**
We need to create a utility module for handling password hashing and verification using bcrypt. This will help ensure the security of user passwords by hashing them before storing in the database and verifying them during authentication.

#### **Tasks**
- **Install Bcrypt**
  - Add bcrypt to the project dependencies.

- **Bcrypt Utility Functions**
  - **hashPassword**
    - Hashes a plain text password.
    - Function signature:
      ```ts
      hashPassword(password: string): Promise<string>
      ```
  - **verifyPassword**
    - Verifies a plain text password against a hashed password.
    - Function signature:
      ```ts
      verifyPassword(password: string, hash: string): Promise<boolean>
      ```

#### **Acceptance Criteria**
- [x] Bcrypt installed and configured.
- [x] `hashPassword` function implemented and tested.
- [x] `verifyPassword` function implemented and tested.
- [ ] Utility functions are used appropriately in the authentication workflow.

#### **Related Documentation**
- Bcrypt Documentation: https://www.npmjs.com/package/bcrypt
- Authentication Workflow Documentation
