### ISSUE TITLE
Add mongoose service

### ISSUE THREAD

**Issue by Darkmift** [Darkmift/ELEVATION-ITWORKS#40]
#### **Description**
We need to set up Mongoose for our application, define the models for Build and Admin using the provided interfaces, and create a build service to handle various operations related to builds.

#### **Tasks**
- **Install Mongoose**
  - Add Mongoose to the project dependencies.
  - Set up Mongoose connection in the project.

- **Add Mongoose Models**
  - **Admin Model**
    - Define the schema using the `IAdmin` interface to extend your schema with the following fields:
      ```
      username: String, unique, required.
      password: String, required.
      role: Number, required, with specific values (1, 2, 3).
      firstName: String, required.
      lastName: String, required.
      ```
  - **Build Model**
    - Define the schema using the `IBuild` interface to extend your schema with the following fields:
      ```
      buildId: String, unique, required.
      status: String, required, with specific values ('success', 'failed', 'canceled').
      caption: String, required.
      command: String, required.
      startTime: Date, required.
      endTime: Date, required.
      errorsNumber: Number, required.
      warningsNumber: Number, required.
      ```

- **Add Build Service**
  - Implement the build service methods:
    - **getBuildsPaginated**
      - Function signature:
        ```ts
        getBuildsPaginated(pagination: Pagination): Promise<Build[]>
        ```
      - Takes pagination object from the parameters.
      - Returns a paginated list of builds.
      - Logs errors and returns an empty array on error.
      
    - **getBuildById**
      - Function signature:
        ```ts
        getBuildById(id: string): Promise<Build | null>
        ```
      - Takes id from the parameters.
      - Returns a build by its ID.
      - Logs errors and returns null on error.

    - **getBuildGroupedByWeek**
      - Function signature:
        ```ts
        getBuildGroupedByWeek(): Promise<BuildCountWeekly>
        ```
      - Returns builds grouped by week.
      - Logs errors and returns an empty object on error.

#### **Acceptance Criteria**
- [ ] Mongoose installed and configured.
- [ ] Admin and Build models created using the `IAdmin` and `IBuild` interfaces, respectively.
- [ ] Build service methods `getBuildsPaginated`, `getBuildById`, and `getBuildGroupedByWeek` implemented and tested.
- [ ] Errors are logged appropriately, and methods return fallback values on error (`[]` for `getBuildsPaginated`, `null` for `getBuildById`, and `{}` for `getBuildGroupedByWeek`).

#### **Additional Notes**
- Ensure adherence to existing coding standards and practices.
- Verify that Mongoose connection is stable and models are properly linked.
- Test the build service methods thoroughly.

#### **Related Documentation**
- Mongoose Documentation: https://mongoosejs.com/docs/guide.html
- Project API Endpoints: /builds

**Comment by Darkmift** [comment]
#56 PR for issue

**Comment by Darkmift** [comment]
> Do I have tasks here for today?
> 
> The service does not have POST, PUT, DELETE, but as I understood - these tasks will be given later at phase 2?

pick from available exisitng open issues.
