### ISSUE TITLE
Add JWT Util,middleware

### ISSUE THREAD

**Issue by Darkmift** [Darkmift/ELEVATION-ITWORKS#41]
#### **Description**
We need to implement token generation and verification functions for handling authentication. Additionally, we need a middleware to check the authentication status of requests.

#### **Tasks**
- **Token Functions**
  - **generateToken**
    - Generates a token for the given payload.
    - Function signature:
      ```ts
      generateToken<T>(payload: T): string
      ```
  - **verifyToken**
    - Verifies the given token and decodes it.
    - Logs error if any.
    - Function signature:
      ```ts
      verifyToken<T>(token: string): { decoded: T } | null
      ```

- **Authentication Middleware**
  - **checkAuth**
    - Checks the authentication status of requests.
    - Retrieves token from `cookies['access-token']`.
    - Decodes and verifies the token, ensuring it contains at least `{id, username, role}`.
    - Function signature:
      ```ts
      checkAuth(req: Request, res: Response, next: NextFunction): void
      ```

#### **Acceptance Criteria**
- [ ] `generateToken` function implemented and tested.
- [ ] `verifyToken` function implemented and tested, with error logging.
- [ ] `checkAuth` middleware implemented and tested.
- [ ] Middleware correctly retrieves and verifies token from cookies.

#### **Related Documentation**
- Authentication Methods
- Middleware Implementation

**Comment by Darkmift** [comment]
added PR #64
