### ISSUE TITLE
Issue: Add Builds Controller and Router

### ISSUE THREAD

**Issue by Darkmift** [Darkmift/ELEVATION-ITWORKS#42]
#### **Description**
We need to implement the builds controller and router for handling various builds-related API requests. The controller will manage the logic, while the router will define the endpoints and their corresponding handlers.

#### **Tasks**
- **Controller Implementation**
  - **getBuildsPaginated** (public)
    - Fetch a paginated list of builds.
    - Function signature:
      ```ts
      getBuildsPaginated(req: Request, res: Response) // takes Pagination from req.query, returns {builds, total}
      ```
  - **getBuildById** (public)
    - Fetch a single build by its ID.
    - Function signature:
      ```ts
      getBuildById(req: Request, res: Response) // takes buildId from req.params, returns {build}
      ```
  - **getBuildGroupedByWeek** (public)
    - Fetch builds grouped by week, counting the number of builds started each week.
    - Aggregation logic to group by `startTime` week and return count.
    - Function signature:
      ```ts
      getBuildGroupedByWeek(req: Request, res: Response) // returns {BuildCountWeekly}
      ```
  - **createBuild** (admin)
    - Create a new build.
    - Function signature:
      ```ts
      createBuild(req: Request, res: Response) // takes Build data from req.body, returns {newBuild}
      ```
  - **editBuild** (admin)
    - Edit an existing build.
    - Function signature:
      ```ts
      editBuild(req: Request, res: Response) // takes buildId from req.params and updated Build data from req.body, returns {updatedBuild}
      ```
  - **deleteBuild** (admin)
    - Delete a build by its ID.
    - Function signature:
      ```ts
      deleteBuild(req: Request, res: Response) // takes buildId from req.params, returns {message: 'Build deleted'}
      ```

- **Router Implementation**
  - Define the following routes:
    - **GET** `/builds?page&limit&sort[keyof Build]`
    - **GET** `/builds/single/:id`
    - **GET** `/builds/grouped`
    - **POST** `/builds`
    - **PUT** `/builds/:id`
    - **DELETE** `/builds/:id`
  - Attach the appropriate middleware for authentication and authorization, such as `checkJwt` for admin routes.

- **Middleware**
  - Integrate `checkJwt` to protect admin routes.

#### **Acceptance Criteria**
- [x] Controller methods implemented and tested.
- [x] Routes defined and linked to controller methods.
- [x] Middleware applied to protect routes.
- [ ] Unit tests for each endpoint.

#### **Related Documentation**
- API Endpoints: /auth, /builds
- Models: Admin, Build
