### ISSUE TITLE
Create Redux Store Slices for Auth and Builds

### ISSUE THREAD

**Issue by Darkmift** [Darkmift/ELEVATION-ITWORKS#43]
#### **Description**
We need to implement Redux slices for managing authentication and builds state in the application. The `auth.slice` will handle authentication-related state and actions, while the `builds.slice` will manage state related to builds.

#### **Tasks**
- **Create Auth Slice**
  - **State**
    - Define `admin` state to hold the logged-in admin's username.
  - **Reducers**
    - **setUser**
      - Sets the `admin` state.
      - Function signature:
        ```ts
        setUser(admin: Admin | null): void
        ```

- **Create Builds Slice**
  - **State**
    - Define `buildsPage` state to hold an array of builds.
    - Define `pagination` state to manage pagination details, structured as:
      ```ts
      { Pagination(page: number, limit: number, sort: string) }
      ```
    - Define `buildsPerWeek` state to hold the count of builds per week for graphing purposes.
  - **Reducers**
    - **setBuilds**
      - Sets the `buildsPage` and `pagination` state.
      - Function signature:
        ```ts
        setBuilds(data: { buildsPage: Build[], pagination: Pagination }): void
        ```
    - **setBuildsPerWeek**
      - Sets the `buildsPerWeek` state.
      - Function signature:
        ```ts
        setBuildsPerWeek(buildsPerWeek: BuildCountWeekly): void
        ```

#### **Acceptance Criteria**
- [x] `auth.slice` created with `admin` state and `setUser` reducer.
- [x] `builds.slice` created with `buildsPage`, `pagination`, and `buildsPerWeek` state.
- [x] `setBuilds` and `setBuildsPerWeek` reducers implemented and tested.
- [x] State and reducers are properly integrated into the Redux store.

#### **Related Documentation**
- Redux Toolkit Documentation: https://redux-toolkit.js.org/
- Project State Management Documentation
