### ISSUE TITLE
Add `<Graph  />` Component @Thetomre

### ISSUE THREAD

**Issue by Darkmift** [Darkmift/ELEVATION-ITWORKS#45]
#### **Description**
We need to implement a `<Graph />` component for visualizing data, using the `react-chartjs-2` library. This component should be integrated with the Redux store and typed appropriately.

#### **Tasks**
- **Install Dependencies**
  - Add `react-chartjs-2` and `chart.js` to the project dependencies.

- **Create Graph Component**
  - Create a `<Graph />` component that utilizes `react-chartjs-2` for rendering charts.

- **Integrate with Redux**
  - Connect the `<Graph />` component to the Redux store.
  - Use selectors to fetch the relevant data from the state.

- **Type Definitions**
  - Define types for the data and props used by the `<Graph />` component.
  - Ensure that all interactions with the Redux store are correctly typed.

- **Graph Component Implementation**
  - Implement the component to handle the following:
    - **Redux Integration:** 
      - Fetch data from the Redux store.
      - Handle loading and error states.

- **Update Redux Store**
  - Ensure the relevant data for the graph is available in the Redux store.
  - Add actions and reducers if necessary to handle the graph data.

#### **Acceptance Criteria**
- [ ] `react-chartjs-2` and `chart.js` installed and configured.
- [ ] `<Graph />` component created and integrated with Redux.
- [ ] Types for the graph

**Comment by Darkmift** [comment]
@TheTomre waiting for you to join to take this

**Comment by TheTomre** [comment]
Got it.
Tanks for a such detailed description!
I just wonder if in the end there is some missing information maybe? 


Acceptance Criteria
 react-chartjs-2 and chart.js installed and configured.
 <Graph /> component created and integrated with Redux.
 Types for the gra  ????

**Comment by Darkmift** [comment]
Yes you'll need some perquisites.
I fixed the typo
