### ISSUE TITLE
Add Cross-Env for Windows/Linux Support

### ISSUE THREAD

**Issue by Darkmift** [Darkmift/ELEVATION-ITWORKS#50]
#### **Description**
We need to ensure that environment variables are set correctly across different operating systems, specifically Windows and Linux. Adding `cross-env` will allow us to define environment variables in a platform-agnostic way in our npm scripts.

#### **Tasks**
- **Install Cross-Env**
  - Add `cross-env` to the project dependencies.

- **Update NPM Scripts**
  - Modify existing npm scripts to use `cross-env` for setting environment variables.
  - Example:
    ```json
    "scripts": {
      "start": "cross-env NODE_ENV=development node server.js",
      "build": "cross-env NODE_ENV=production webpack --config webpack.config.js"
    }
    ```

- **Test NPM Scripts**
  - Ensure that the npm scripts work correctly on both Windows and Linux environments.
  - Verify that environment variables are set as expected.

#### **Acceptance Criteria**
- [ ] `cross-env` installed and added to project dependencies.
- [ ] NPM scripts updated to use `cross-env` for setting environment variables.
- [ ] NPM scripts tested and verified to work on both Windows and Linux environments.

#### **Related Documentation**
- Cross-Env Documentation: https://www.npmjs.com/package/cross-env
- Project Build and Deployment Guidelines

**Comment by Darkmift** [comment]
update on this?

**Comment by AndreevSV** [comment]
No, just understand thast it's mine
