### ISSUE TITLE
`getBuildsPaginated` should return totalCount in additon to build paginationr esult

### ISSUE THREAD

**Issue by Darkmift** [Darkmift/ELEVATION-ITWORKS#68]
#### **Description**
We need to update the `getBuildsPaginated` function to return the total count of builds along with the paginated results. This will allow the frontend to display the total number of builds available, facilitating better pagination controls.

#### **Tasks**
- **Update `getBuildsPaginated` Function**
  - Modify the `getBuilds` function to include `totalCount` in the response.
  - Ensure that the total count of builds is calculated and returned along with the paginated results.

- **Backend Implementation**
  - Adjust the database query to retrieve the total count of builds.
  - Structure the response to include both the `totalCount` and the paginated list of builds.
  - Function signature update:
    ```ts
    getBuildsPaginated(req: Request, res: Response) // returns { builds: Build[], totalCount: number }
    ```

- **Frontend Integration**
  - Ensure that the frontend correctly handles the updated response format.
  - Update any relevant components to use the `totalCount` for pagination purposes.

#### **Acceptance Criteria**
- [ ] `getBuilds` function updated to return `totalCount` and paginated results.
- [ ] Total count of builds is correctly calculated and included in the response.
- [ ] Frontend handles the updated response format and uses `totalCount` for pagination.
- [ ] Refactor /Add Unit tests for the updated `getBuildsPaginated` function.

#### **Related Documentation**
- API Endpoints: /builds
- Project State Management and Pagination Guidelines
