### ISSUE TITLE
Refactor Controllers and Middlewares to Use Standardized Types

### ISSUE THREAD

**Issue by Darkmift** [Darkmift/ELEVATION-ITWORKS#71]
#### **Description**
We need to refactor all controllers and middlewares to use standardized types for `Request`, `Response`, and `NextFunction` from the `express` module. Additionally, we will introduce a `ControllerMethod` interface to ensure consistency across all controller methods.

#### **Tasks**
- **Import Standard Types**
  - Update all controller and middleware files to import the following types from `express`:
    ```ts
    import { Request, Response, NextFunction } from 'express';
    ```

- **Define ControllerMethod Interface**
  - Introduce a `ControllerMethod` interface in a shared types file:
    ```ts
    export interface ControllerMethod<T = void> {
      (req: Request, res: Response, next: NextFunction): T | Promise<T>;
    }
    ```

- **AFTER MERGING THIS**
- **Refactor Controllers**
  - Refactor all controller methods to use the `ControllerMethod` interface.
  - Ensure that all methods adhere to the new interface definition.

- **Refactor Middlewares**
  - Refactor all middleware functions to use the `Request`, `Response`, and `NextFunction` types.
  - Ensure consistency and type safety across all middlewares.

#### **Acceptance Criteria**
- [ ] All controllers and middlewares import `Request`, `Response`, and `NextFunction` from `express`.
- [ ] `IMPLEMENT REFACTOR AFTER this is merged`
- [ ] `ControllerMethod` interface introduced and used in all controller methods.
- [ ] All controller methods refactored to use the `ControllerMethod` interface.
- [ ] Middlewares refactored to use standardized types.
- [ ] Codebase reviewed to ensure type safety and consistency.

#### **Related Documentation**
- Express TypeScript Documentation: https://expressjs.com/en/advanced/best-practice-performance.html
- Project TypeScript Guidelines
