### ISSUE TITLE
Feature auth endpoint

### ISSUE THREAD

**Issue by Darkmift** [Darkmift/ELEVATION-ITWORKS#77]
#### **Description**
We need to implement authentication on the server side. This includes creating the Admin model, implementing the authentication service, controller, and middleware for validating username and password using Joi.

#### **Tasks**
- **Create Admin Model**
  - Define the Admin schema and model with the following fields:
    - `username`
    - `password`
    - `role`
    - `firstName`
    - `lastName`

- **Implement Auth Service**
  - Implement the authentication service with a `login` function.
    - **login**
      ```ts
      login(username: string, password: string): Promise<{ token: string } | null>
      ```
  - The `login` function should validate the user's credentials and return a JWT token if successful.

- **Implement Auth Controller**
  - Implement the authentication controller to handle login requests.
    - **login**
      ```ts
      login(req: Request, res: Response, next: NextFunction): Promise<Response>
      ```

- **Implement Middleware**
  - Implement middleware for validating the username and password using Joi.
    - **Username and Password Validation Middleware**
      ```ts
      validateCredentials(req: Request, res: Response, next: NextFunction): void
      ```
    - Use Joi to define the validation schema for username and password.

#### **Acceptance Criteria**
- [x] Admin model created with the required fields.
- [x] Auth service implemented with a `login` function.
- [x] Auth controller implemented to handle login requests.
- [x] Middleware for validating username and password using Joi implemented.
- [ ] Authentication flow tested end-to-end, ensuring valid credentials return a JWT token and invalid credentials return appropriate errors.
- [ ] Unit tests for the auth service, controller, and middleware.

#### **Related Documentation**
- Joi Documentation: https://joi.dev/api/
- JWT Documentation: https://jwt.io/
- Project Authentication Guidelines
